# -*- coding: utf-8 -*-

users = {
    # 'title' tag used in item links.
    'item_title': 'list',

    'additional_lookup': {
        'url': '[\w]+',
        'field': 'email'
    },

    # Schema definition, based on Cerberus grammar. Check the Cerberus project
    # (https://github.com/nicolaiarocci/cerberus) for details.
    'schema': {
    # _id field is the default primary key autogenerated by mongodb
        # 'ID': {
        #     'type': 'objectid',
        #     'required': True,
        #     'unique': True,
        # },
        'type': {
            'type': 'string',
            'empty': False,
            'required': True,
        },
        'email': {
            'type': 'string',
            'empty': False,
            'required': True,
            'unique': True,
        },
        'name': {
            'type': 'string',
            'required': True,
            'empty': False,
        },
        'links': {
            'type': 'boolean',
            'required': True,
        },
        'link_image_urls': {
            'type': 'list'
        },
        'note': {
            'type': 'string',
            'required': False,
        }
    },
}
